function run_mosaicSubTiles(...
    tileName,quadrant,tileDefFile,...
    subTileDir,resolution,outMatFile,...
    projection,version,exportTif...
)

if exportTif
    outRasterType = 'COG';
else
    outRasterType = 'browse';
end

try
    if ~isempty(version)
        version = strrep(version, ',', '|');
    end
    if isempty(quadrant)
        [x0,x1,y0,y1] = getTileExtents(tileName,tileDefFile);
        mosaicSubTiles(subTileDir,resolution,outMatFile,...
            'projection',projection,...
            'version',version,...
            'outRasterType',outRasterType,...
            'extent',[x0,x1,y0,y1]...
        )
    else
        [x0,x1,y0,y1] = getTileExtents(tileName,tileDefFile,'quadrant',quadrant);
        mosaicSubTiles(subTileDir,resolution,outMatFile,...
            'projection',projection,...
            'version',version,...
            'quadrant',quadrant,...
            'outRasterType',outRasterType,...
            'extent',[x0,x1,y0,y1]...
        )
    end
catch e
    disp(getReport(e)); exit(1)
end

exit(0)
