function run_mosaicSubTiles(...
    tileName,quadrant,tileDefFile,...
    subTileDir,resolution,outMatFile,...
    projection,version...
)

try
    if isempty(quadrant)
        [x0,x1,y0,y1] = getTileExtents(tileName,tileDefFile);
        mosaicSubTiles(subTileDir,resolution,outMatFile,...
            'projection',projection,...
            'version',version,...
            'extent',[x0,x1,y0,y1]...
        )
    else
        [x0,x1,y0,y1] = getTileExtents(tileName,tileDefFile,'quadrant',quadrant);
        mosaicSubTiles(subTileDir,resolution,outMatFile,...
            'projection',projection,...
            'version',version,...
            'quadrant',quadrant,...
            'extent',[x0,x1,y0,y1]...
        )
    end
catch e
    disp(getReport(e)); exit(1)
end

exit(0)
