function run_buildSubTiles(...
    tileName,outDir,resolution,...
    projection,tileDefFile,...
    stripDatabaseFile,stripsDirectory,...
    waterTileDir,refDemFile,...
    tileqcDir,tileParamListFile,...
    make2m...
)

try
    [meta,landTile,buffer,minStripOverlap,filterFlag] = initializeMosaic('',tileName,'',...
        'res',resolution,...
        'projection',projection,'tileDefFile',tileDefFile,...
        'stripDatabaseFile',stripDatabaseFile,'stripsDirectory',stripsDirectory,...
        'waterTileDir',waterTileDir,'refDemFile',refDemFile,...
        'tileqcDir',tileqcDir,'tileParamListFile',tileParamListFile,...
        'returnMetaOnly',true...
    );
    buildSubTiles(tileName,outDir,tileDefFile,meta,...
        'landTile',landTile,...
        'refDemFile',refDemFile,...
        'buffer',buffer,...
        'minStripOverlap',minStripOverlap,...
        'filter',filterFlag,...
        'projection',projection,...
        'res',resolution,...
        'make2m',make2m...
    )
catch e
    disp(getReport(e)); exit(1)
end

exit(0)
