"""
The purpose of this script is to identify the direct and indirect dependencies a custom
Matlab function has on other custom Matlab functions within the same repository. This
script will not identify dependencies from external repositories that are brought into
scope using addpath(/path/to/more/matlab/functions).

This script was generated by claude.ai and lightly edited.
"""

from pathlib import Path
import re
from collections import defaultdict


def find_matlab_files(root_dir: Path) -> list[Path]:
    """Find all .m files in the given directory and subdirectories."""
    return list(root_dir.rglob("*.m"))


def extract_function_name(filepath: Path) -> str:
    """Extract the main function name from a MATLAB file."""
    content = filepath.read_text(encoding="utf-8")

    # Look for function definition
    match = re.search(
        r"^\s*function\s+(?:\[?[\w\s,]+\]?\s*=\s*)?(\w+)", content, re.MULTILINE
    )
    if match:
        return match.group(1)
    # If no function definition found, use filename without extension
    return filepath.stem


def find_function_calls(filepath: Path) -> set[str]:
    """Find all function calls in a MATLAB file."""
    content = filepath.read_text(encoding="utf-8")

    # Remove comments
    content = re.sub(r"%.*$", "", content, flags=re.MULTILINE)
    content = re.sub(r"(?s)/\*.*?\*/", "", content)

    # Find function calls
    # This regex looks for word characters followed by opening parenthesis
    function_calls = set(re.findall(r"(?<!\.)\b(\w+)\s*\(", content))

    return function_calls


def build_dependency_graph(
    repo_path: Path,
) -> tuple[dict[str, set[str]], dict[str, Path]]:
    """Build a dependency graph for all MATLAB files in the repository."""
    matlab_files = find_matlab_files(repo_path)

    # Create mapping of function names to file paths
    function_to_file: dict[str, Path] = {}
    for filepath in matlab_files:
        function_name = extract_function_name(filepath)
        function_to_file[function_name] = filepath

    # Build dependency graph
    dependencies: dict[str, set[str]] = defaultdict(set)
    for filepath in matlab_files:
        main_function = extract_function_name(filepath)
        called_functions = find_function_calls(filepath)

        # Only include calls to functions that exist in the repository
        repo_function_calls = {
            func for func in called_functions if func in function_to_file
        }
        dependencies[main_function].update(repo_function_calls)

    return dependencies, function_to_file


def get_all_dependencies(
    function_name: str,
    dependencies: dict[str, set[str]],
    direct_deps: set[str],
    visited: set[str] | None = None,
) -> set[str]:
    """Recursively find all indirect dependencies for a given function."""
    if visited is None:
        visited = set()

    if function_name in visited:
        return visited

    visited.add(function_name)
    for dep in dependencies.get(function_name, []):
        get_all_dependencies(dep, dependencies, direct_deps, visited)

    # Remove the original function and direct dependencies from the result
    return visited - {function_name} - direct_deps


def analyze_dependencies(repo_path: Path, target_function: str) -> str:
    """Analyze dependencies for a specific MATLAB function in the repository."""
    dependencies, function_to_file = build_dependency_graph(repo_path)

    if target_function not in function_to_file:
        return f"Error: Function '{target_function}' not found in repository."

    # Get direct dependencies
    direct_deps = dependencies[target_function]

    # Get indirect dependencies (excluding direct ones)
    indirect_deps = get_all_dependencies(target_function, dependencies, direct_deps)

    # Format results
    result = [f"Dependencies for {target_function}:"]

    if direct_deps:
        result.append("\nDirect dependencies:")
        for dep in sorted(direct_deps):
            result.append(f"- {dep} ({function_to_file[dep].name})")
    else:
        result.append("\nNo direct dependencies found.")

    if indirect_deps:
        result.append("\nIndirect dependencies:")
        for dep in sorted(indirect_deps):
            result.append(f"- {dep} ({function_to_file[dep].name})")
    else:
        result.append("\nNo indirect dependencies found.")

    return "\n".join(result)


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 3:
        script = Path(__file__).name
        print(f"Usage: python {script} <repository_path> <target_function>")
        sys.exit(1)

    repo_path = Path(sys.argv[1])
    target_function = sys.argv[2]
    print(analyze_dependencies(repo_path, target_function))
